# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gMADD <- function(s_psi, s_h, n_clust, lb, M) {
    .Call(`_HDLSSkST_gMADD`, s_psi, s_h, n_clust, lb, M)
}

gMADD_DI <- function(s_psi, s_h, kmax, lb, M) {
    .Call(`_HDLSSkST_gMADD_DI`, s_psi, s_h, kmax, lb, M)
}

rctab <- function(M) {
    .Call(`_HDLSSkST_rctab`, M)
}

